server:
  port: 80
logging:
  file:
    name: empty.log
    max-history: 10
    max-size: 2MB
  pattern:
    rolling-file-name: empty.%d{yyyy-MM-dd}.%i.log



# 自定义字符常量
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
type: "application/x-www-form-urlencoded; charset=UTF-8"
url: "https://jwxt.bistu.edu.cn/jwapp/sys/kxjas/modules/kxjscx/cxkxjs.do"
referer: "https://jwxt.bistu.edu.cn/jwapp/sys/kxjas/*default/index.do?EMAP_LANG=zh"

