name: Build Native Executable with GraalVM

on:
  push:
    branches:
      - master # 修改成你的默认分支名称

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.2'
        java-version: '17'

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Build with Maven
      run: mvn clean package

    - name: Install native-image
      run: gu install native-image

    - name: Build native executable
      run: mvn -Pnative native:compile

    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: target
