name: Build Native Executable with GraalVM

on:
  push:
    branches:
      - master # 修改成你的默认分支名称
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.2'
        java-version: '17'

    - name: Install Maven
      run: |
        wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
        tar -xzf apache-maven-3.8.4-bin.tar.gz
        sudo mv apache-maven-3.8.4 /opt/maven
        echo "M2_HOME=/opt/maven" | sudo tee -a /etc/environment
        echo "PATH=\$M2_HOME/bin:\$PATH" | sudo tee -a /etc/environment
        source /etc/environment

    - name: Install native-image
      run: gu install native-image

    - name: Build native executable
      run: mvn -Pnative native:compile

    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: target
